version: "1"
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=minumero1
      - POSTGRES_DB=gana_premios_db

    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: "./gana-premios-app"
      dockerfile: DockerFile.dev
    
    ports:
    #    HOST-PORT: CONTAINER-PORT
      - "3000:3000"
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - "./gana-premios-app:/app"

volumes:
  postgres_data: {}
